# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 冷石
description: 孑然一身，傲立于世
keywords: '冷石, 前端, 面试，Web, Js, CSS, Node.js, Frontend, Flutter, Docker, Dart, Mysql, Egg.js'
author: ColdStone
language: zh
timezone: Asia/Shanghai
# blog config
seo_title: 冷石的博客

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://coldstone.fun
root: /
permalink: :route/:year/:month/:day/:title/
permalink_defaults:
  route: post

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: true
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 21
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cold-stone

# user config
avatar: avatar.jpg
zanshang: zanshang.jpg

# Utteranc comment system
comment:
  repo: xrr2016/blog

# sns link：
sns:
  github: xrr2016
  zhihu: needforchange
  juejin: 576666b7207703006b1e0f09
  leetcode: coldstone
  # segmentfault: taqianzhan

# RSS
# rss: true
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content: true
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: avatar.png
  autodiscovery: true

all_minifier: false
